name: Release

on:
  schedule:
    - cron: '0 0 * * Mon'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update'
        required: false
        default: 'false'

jobs:
  crawl:
    name: Crawl Domains
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: false

      - name: Env
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          

      - name: Build .dat file
        run: |
          git clone https://github.com/v2fly/domain-list-community
          rm -rf domain-list-community/data/*
          
          mv output/ir_domains.txt domain-list-community/data/arv
          cd domain-list-community
          go run ./ --outputdir=../output
          cd ../output
          mv dlc.dat my.dat


      - name: Upload result as release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.*"
          body: "${{ env.TOTAL_DOMAINS }} Domains"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
